require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TravelsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Travel. As you add validations to Travel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TravelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all travels as @travels" do
      travel = Travel.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:travels)).to eq([travel])
    end
  end

  describe "GET show" do
    it "assigns the requested travel as @travel" do
      travel = Travel.create! valid_attributes
      get :show, {:id => travel.to_param}, valid_session
      expect(assigns(:travel)).to eq(travel)
    end
  end

  describe "GET new" do
    it "assigns a new travel as @travel" do
      get :new, {}, valid_session
      expect(assigns(:travel)).to be_a_new(Travel)
    end
  end

  describe "GET edit" do
    it "assigns the requested travel as @travel" do
      travel = Travel.create! valid_attributes
      get :edit, {:id => travel.to_param}, valid_session
      expect(assigns(:travel)).to eq(travel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Travel" do
        expect {
          post :create, {:travel => valid_attributes}, valid_session
        }.to change(Travel, :count).by(1)
      end

      it "assigns a newly created travel as @travel" do
        post :create, {:travel => valid_attributes}, valid_session
        expect(assigns(:travel)).to be_a(Travel)
        expect(assigns(:travel)).to be_persisted
      end

      it "redirects to the created travel" do
        post :create, {:travel => valid_attributes}, valid_session
        expect(response).to redirect_to(Travel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved travel as @travel" do
        post :create, {:travel => invalid_attributes}, valid_session
        expect(assigns(:travel)).to be_a_new(Travel)
      end

      it "re-renders the 'new' template" do
        post :create, {:travel => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested travel" do
        travel = Travel.create! valid_attributes
        put :update, {:id => travel.to_param, :travel => new_attributes}, valid_session
        travel.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested travel as @travel" do
        travel = Travel.create! valid_attributes
        put :update, {:id => travel.to_param, :travel => valid_attributes}, valid_session
        expect(assigns(:travel)).to eq(travel)
      end

      it "redirects to the travel" do
        travel = Travel.create! valid_attributes
        put :update, {:id => travel.to_param, :travel => valid_attributes}, valid_session
        expect(response).to redirect_to(travel)
      end
    end

    describe "with invalid params" do
      it "assigns the travel as @travel" do
        travel = Travel.create! valid_attributes
        put :update, {:id => travel.to_param, :travel => invalid_attributes}, valid_session
        expect(assigns(:travel)).to eq(travel)
      end

      it "re-renders the 'edit' template" do
        travel = Travel.create! valid_attributes
        put :update, {:id => travel.to_param, :travel => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested travel" do
      travel = Travel.create! valid_attributes
      expect {
        delete :destroy, {:id => travel.to_param}, valid_session
      }.to change(Travel, :count).by(-1)
    end

    it "redirects to the travels list" do
      travel = Travel.create! valid_attributes
      delete :destroy, {:id => travel.to_param}, valid_session
      expect(response).to redirect_to(travels_url)
    end
  end

end
